// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Js_promise from "@rescript/runtime/lib/es6/Js_promise.js";
import * as Notification from "./Notification.res.js";

let state = {
  currentTab: "generate",
  wasmReady: false,
  processing: false
};

function escapeHtml(text) {
  let div = document.createElement("div");
  div.textContent = text;
  return div.innerHTML;
}

function $$parseInt(s) {
  let result = (parseInt(s, 10));
  if ((isNaN(result))) {
    return 0;
  } else {
    return result;
  }
}

function setFormLoading(form, loading) {
  (((function(form, loading) {
      var btn = form.querySelector('button[type="submit"]');
      if (loading) {
        form.classList.add('loading');
        if (btn) { btn.disabled = true; btn.textContent = 'Processing...'; }
      } else {
        form.classList.remove('loading');
        if (btn) { btn.disabled = false; btn.textContent = btn.getAttribute('data-original-text') || 'Submit'; }
      }
    }))(form, loading));
}

function setupTabNavigation() {
  let tabButtons = document.querySelectorAll(".tab-button");
  let tabPanels = document.querySelectorAll(".tab-panel");
  Belt_Array.forEach(tabButtons, button => {
    button.addEventListener("click", () => {
      let tabName = button.getAttribute("data-tab");
      if (tabName == null) {
        return;
      }
      Belt_Array.forEach(tabButtons, btn => {
        btn.classList();
        ((btn.classList.remove('active')));
        btn.setAttribute("aria-selected", "false");
      });
      ((button.classList.add('active')));
      button.setAttribute("aria-selected", "true");
      Belt_Array.forEach(tabPanels, panel => {
        panel.hidden = true;
      });
      let activePanel = document.getElementById(tabName);
      if (!(activePanel == null)) {
        activePanel.hidden = false;
        state.currentTab = tabName;
        return;
      }
    });
  });
}

function setupGenerateForm() {
  let form = document.getElementById("generate-form");
  if (!(form == null)) {
    document.getElementById("generate-output");
    ((form.addEventListener('submit', async function(e) {
          e.preventDefault();

          if (!window.__RESCRIPT_APP_STATE__.wasmReady) {
            window.__RESCRIPT_NOTIFICATION__.show('WASM modules not ready yet. Please wait...', 'warning');
            return;
          }

          if (window.__RESCRIPT_APP_STATE__.processing) {
            window.__RESCRIPT_NOTIFICATION__.show('Already processing. Please wait...', 'warning');
            return;
          }

          var genType = form.querySelector('#gen-type').value;
          var count = parseInt(form.querySelector('#gen-count').value, 10);
          var minLength = parseInt(form.querySelector('#gen-min').value, 10);
          var maxLength = parseInt(form.querySelector('#gen-max').value, 10);

          if (count < 1 || count > 10000) {
            window.__RESCRIPT_NOTIFICATION__.show('Count must be between 1 and 10,000', 'error');
            return;
          }

          if (minLength > maxLength) {
            window.__RESCRIPT_NOTIFICATION__.show('Min length cannot be greater than max length', 'error');
            return;
          }

          window.__RESCRIPT_APP_STATE__.processing = true;
          window.__RESCRIPT_SET_FORM_LOADING__(form, true);

          try {
            var startTime = performance.now();
            var passwords = window.__RESCRIPT_GENERATORS__.generate(genType, count, minLength, maxLength);
            var endTime = performance.now();
            var elapsed = ((endTime - startTime) / 1000).toFixed(2);

            var outputPanel = document.getElementById('generate-output');
            var outputStats = outputPanel.querySelector('.output-stats');
            var outputContent = outputPanel.querySelector('.output-content');

            outputStats.innerHTML = '<div><strong>' + passwords.length + '</strong><span>Generated</span></div>' +
              '<div><strong>' + genType + '</strong><span>Generator</span></div>' +
              '<div><strong>' + minLength + '-' + maxLength + '</strong><span>Length Range</span></div>' +
              '<div><strong>' + elapsed + 's</strong><span>Time Taken</span></div>';

            outputContent.textContent = passwords.join('\\n');
            outputPanel.hidden = false;

            window.__RESCRIPT_NOTIFICATION__.show('Generated ' + passwords.length + ' passwords in ' + elapsed + 's', 'success');
          } catch (error) {
            console.error('Generation error:', error);
            window.__RESCRIPT_NOTIFICATION__.show('Generation failed: ' + error.message, 'error');
          } finally {
            window.__RESCRIPT_APP_STATE__.processing = false;
            window.__RESCRIPT_SET_FORM_LOADING__(form, false);
          }
        })));
    return;
  }
}

function setupHashForm() {
  let form = document.getElementById("hash-form");
  if (!(form == null)) {
    ((form.addEventListener('submit', async function(e) {
          e.preventDefault();

          if (!window.__RESCRIPT_APP_STATE__.wasmReady) {
            window.__RESCRIPT_NOTIFICATION__.show('WASM modules not ready yet. Please wait...', 'warning');
            return;
          }

          var password = form.querySelector('#hash-input').value;
          var algorithm = form.querySelector('#hash-algo').value;

          if (!password) {
            window.__RESCRIPT_NOTIFICATION__.show('Please enter a password to hash', 'error');
            return;
          }

          window.__RESCRIPT_SET_FORM_LOADING__(form, true);

          try {
            var startTime = performance.now();
            var hash = await window.__RESCRIPT_HASH__.hashPassword(password, algorithm);
            var endTime = performance.now();
            var elapsed = ((endTime - startTime) * 1000).toFixed(2);

            var outputPanel = document.getElementById('hash-output');
            var outputContent = outputPanel.querySelector('.output-content');

            outputContent.textContent = 'Algorithm: ' + algorithm.toUpperCase() + '\\nHash: ' + hash + '\\n\\nTime: ' + elapsed + 'ms';
            outputPanel.hidden = false;

            window.__RESCRIPT_NOTIFICATION__.show('Password hashed using ' + algorithm.toUpperCase(), 'success');
          } catch (error) {
            console.error('Hashing error:', error);
            window.__RESCRIPT_NOTIFICATION__.show('Hashing failed: ' + error.message, 'error');
          } finally {
            window.__RESCRIPT_SET_FORM_LOADING__(form, false);
          }
        })));
    return;
  }
}

function setupCrackForm() {
  let form = document.getElementById("crack-form");
  if (!(form == null)) {
    ((form.addEventListener('submit', async function(e) {
          e.preventDefault();

          if (!window.__RESCRIPT_APP_STATE__.wasmReady) {
            window.__RESCRIPT_NOTIFICATION__.show('WASM modules not ready yet. Please wait...', 'warning');
            return;
          }

          if (window.__RESCRIPT_APP_STATE__.processing) {
            window.__RESCRIPT_NOTIFICATION__.show('Already processing. Please wait...', 'warning');
            return;
          }

          var hash = form.querySelector('#crack-hash').value.trim();
          var algorithm = form.querySelector('#crack-algo').value;
          var generator = form.querySelector('#crack-gen').value;
          var maxAttempts = parseInt(form.querySelector('#crack-max').value, 10);

          if (!hash || !window.__RESCRIPT_HASH__.isValidHash(hash, algorithm)) {
            window.__RESCRIPT_NOTIFICATION__.show('Invalid ' + algorithm.toUpperCase() + ' hash format', 'error');
            return;
          }

          window.__RESCRIPT_APP_STATE__.processing = true;
          window.__RESCRIPT_SET_FORM_LOADING__(form, true);

          try {
            var startTime = performance.now();
            var result = await window.__RESCRIPT_HASH__.crackHashFallback(hash, algorithm, generator, maxAttempts);
            var endTime = performance.now();
            var elapsed = ((endTime - startTime) / 1000).toFixed(2);

            var outputPanel = document.getElementById('crack-output');
            var outputContent = outputPanel.querySelector('.output-content');

            if (result.found) {
              outputContent.innerHTML = '<div class="text-success" style="margin-bottom: 1rem;"><strong>Password Found!</strong></div>' +
                '<div style="margin-bottom: 0.5rem;"><strong>Password:</strong> <code style="color: var(--color-success);">' + result.password + '</code></div>' +
                '<div style="margin-bottom: 0.5rem;"><strong>Attempts:</strong> ' + result.attempts.toLocaleString() + ' / ' + maxAttempts.toLocaleString() + '</div>' +
                '<div style="margin-bottom: 0.5rem;"><strong>Time:</strong> ' + elapsed + 's</div>' +
                '<div><strong>Rate:</strong> ' + Math.floor(result.attempts / elapsed).toLocaleString() + ' hashes/sec</div>';
              window.__RESCRIPT_NOTIFICATION__.show('Password cracked in ' + elapsed + 's!', 'success');
            } else {
              outputContent.innerHTML = '<div class="text-warning" style="margin-bottom: 1rem;"><strong>Password Not Found</strong></div>' +
                '<div style="margin-bottom: 0.5rem;"><strong>Attempts:</strong> ' + maxAttempts.toLocaleString() + '</div>' +
                '<div style="margin-bottom: 0.5rem;"><strong>Time:</strong> ' + elapsed + 's</div>' +
                '<div><strong>Rate:</strong> ' + Math.floor(maxAttempts / elapsed).toLocaleString() + ' hashes/sec</div>' +
                '<div style="margin-top: 1rem; color: var(--color-text-muted);">Try increasing max attempts or using a different generator.</div>';
              window.__RESCRIPT_NOTIFICATION__.show('Password not found. Try different settings.', 'warning');
            }

            outputPanel.hidden = false;
          } catch (error) {
            console.error('Cracking error:', error);
            window.__RESCRIPT_NOTIFICATION__.show('Cracking failed: ' + error.message, 'error');
          } finally {
            window.__RESCRIPT_APP_STATE__.processing = false;
            window.__RESCRIPT_SET_FORM_LOADING__(form, false);
          }
        })));
    return;
  }
}

function copyOutput(panelId) {
  let panel = document.getElementById(panelId);
  if (panel == null) {
    return;
  }
  let content = panel.querySelector(".output-content");
  if (content == null) {
    return;
  }
  let text = content.textContent;
  let __x = navigator.clipboard.writeText(text);
  let __x$1 = Js_promise.then_(() => {
    Notification.show("Copied to clipboard!", "Success");
    return Promise.resolve();
  }, __x);
  Js_promise.$$catch(param => {
    Notification.show("Failed to copy to clipboard", "Error");
    return Promise.resolve();
  }, __x$1);
}

function enableForms() {
  let forms = document.querySelectorAll(".tool-form");
  Belt_Array.forEach(forms, form => {
    let btn = form.querySelector(`button[type="submit"]`);
    if (!(btn == null)) {
      btn.disabled = false;
      return;
    }
  });
}

function initialize() {
  console.log("Initializing dicti0nary-attack application");
  ((window.__RESCRIPT_APP_STATE__ = { wasmReady: false, processing: false };
    window.__RESCRIPT_SET_FORM_LOADING__ = function(form, loading) {
      var btn = form.querySelector('button[type="submit"]');
      if (loading) {
        form.classList.add('loading');
        if (btn) { btn.disabled = true; btn.textContent = 'Processing...'; }
      } else {
        form.classList.remove('loading');
        if (btn) { btn.disabled = false; btn.textContent = btn.getAttribute('data-original-text') || 'Submit'; }
      }
    };));
  setupTabNavigation();
  setupGenerateForm();
  setupCrackForm();
  setupHashForm();
  window.addEventListener("wasm-ready", () => {
    console.log("WASM ready, enabling forms");
    state.wasmReady = true;
    ((window.__RESCRIPT_APP_STATE__.wasmReady = true));
    enableForms();
  });
  ((window.copyOutput = function(panelId) {
    var panel = document.getElementById(panelId);
    if (!panel) return;
    var content = panel.querySelector('.output-content');
    if (!content) return;
    navigator.clipboard.writeText(content.textContent).then(function() {
      window.__RESCRIPT_NOTIFICATION__.show('Copied to clipboard!', 'success');
    }).catch(function(err) {
      console.error('Copy failed:', err);
      window.__RESCRIPT_NOTIFICATION__.show('Failed to copy to clipboard', 'error');
    });
  }));
  let style = document.createElement("style");
  style.textContent = `
    @keyframes slideIn {
      from { transform: translateX(100%); opacity: 0; }
      to { transform: translateX(0); opacity: 1; }
    }
    @keyframes slideOut {
      from { transform: translateX(0); opacity: 1; }
      to { transform: translateX(100%); opacity: 0; }
    }
  `;
  ((document.head.appendChild(style)));
  console.log("Application initialized");
}

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", initialize);
} else {
  initialize();
}

export {
  state,
  escapeHtml,
  $$parseInt,
  setFormLoading,
  setupTabNavigation,
  setupGenerateForm,
  setupHashForm,
  setupCrackForm,
  copyOutput,
  enableForms,
  initialize,
}
/*  Not a pure module */
