// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function generatorTypeFromString(s) {
  switch (s) {
    case "leetspeak" :
      return "Leetspeak";
    case "markov" :
      return "Markov";
    case "pattern" :
      return "Pattern";
    case "phonetic" :
      return "Phonetic";
    case "random" :
      return "Random";
    default:
      return;
  }
}

function generatorTypeToString(g) {
  switch (g) {
    case "Leetspeak" :
      return "leetspeak";
    case "Phonetic" :
      return "phonetic";
    case "Pattern" :
      return "pattern";
    case "Random" :
      return "random";
    case "Markov" :
      return "markov";
  }
}

function randomInt(max) {
  return Math.random() * max | 0;
}

function randomChar(chars) {
  let idx = randomInt(chars.length);
  return chars.charAt(idx);
}

let leetMap = Object.fromEntries([
  [
    "a",
    "4"
  ],
  [
    "e",
    "3"
  ],
  [
    "i",
    "1"
  ],
  [
    "o",
    "0"
  ],
  [
    "s",
    "5"
  ],
  [
    "t",
    "7"
  ]
]);

let words = [
  "password",
  "admin",
  "login",
  "secure",
  "access",
  "system"
];

function generateLeetspeak(minLen, maxLen) {
  let word = words[randomInt(words.length)];
  let chars = word.split("");
  let result = Belt_Array.map(chars, c => {
    if (Math.random() <= 0.5) {
      return c;
    }
    let replacement = leetMap[c];
    if (replacement !== undefined) {
      return replacement;
    } else {
      return c;
    }
  }).join("");
  let resultRef = result;
  while (resultRef.length < minLen) {
    resultRef = resultRef + String(randomInt(10));
  };
  return resultRef.slice(0, maxLen);
}

let phonetic = [
  "for",
  "to",
  "you",
  "see",
  "why",
  "are",
  "bee",
  "sea"
];

let phoneticNums = [
  "4",
  "2",
  "u",
  "c",
  "y",
  "r",
  "b",
  "c"
];

function generatePhonetic(minLen, maxLen) {
  let result = "";
  let iterations = (maxLen + 2 | 0) / 3 | 0;
  for (let _for = 0; _for < iterations; ++_for) {
    if (result.length < maxLen) {
      let idx = randomInt(phonetic.length);
      result = Math.random() > 0.5 ? result + phonetic[idx] : result + phoneticNums[idx];
    }
  }
  let len = result.length;
  return result.slice(0, Math.min(Math.max(minLen, len), maxLen));
}

let patterns = [
  "qwerty",
  "asdfgh",
  "zxcvbn",
  "123456",
  "qazwsx",
  "qwertyuiop",
  "asdfghjkl",
  "1qaz2wsx",
  "zaq12wsx"
];

function reverseString(s) {
  return Belt_Array.reverse(s.split("")).join("");
}

function generatePattern(minLen, maxLen) {
  let pattern = patterns[randomInt(patterns.length)];
  let result = Math.random() > 0.5 ? reverseString(pattern) : pattern;
  let result$1 = result + String(randomInt(1000));
  let len = result$1.length;
  return result$1.slice(0, Math.min(Math.max(minLen, len), maxLen));
}

let chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

function generateRandom(minLen, maxLen) {
  let length = minLen + randomInt((maxLen - minLen | 0) + 1 | 0) | 0;
  let result = "";
  for (let _for = 0; _for < length; ++_for) {
    result = result + randomChar(chars);
  }
  return result;
}

let bigrams = [
  "th",
  "he",
  "in",
  "er",
  "an",
  "re",
  "on",
  "at",
  "en",
  "ed"
];

function generateMarkov(minLen, maxLen) {
  let length = minLen + randomInt((maxLen - minLen | 0) + 1 | 0) | 0;
  let result = "";
  while (result.length < length) {
    result = result + bigrams[randomInt(bigrams.length)];
  };
  return result.slice(0, length);
}

function generate(genType, count, minLen, maxLen) {
  return Belt_Array.map(Belt_Array.make(count, undefined), () => {
    switch (genType) {
      case "Leetspeak" :
        return generateLeetspeak(minLen, maxLen);
      case "Phonetic" :
        return generatePhonetic(minLen, maxLen);
      case "Pattern" :
        return generatePattern(minLen, maxLen);
      case "Random" :
        return generateRandom(minLen, maxLen);
      case "Markov" :
        return generateMarkov(minLen, maxLen);
    }
  });
}

export {
  generatorTypeFromString,
  generatorTypeToString,
  randomInt,
  randomChar,
  leetMap,
  words,
  generateLeetspeak,
  phonetic,
  phoneticNums,
  generatePhonetic,
  patterns,
  reverseString,
  generatePattern,
  chars,
  generateRandom,
  bigrams,
  generateMarkov,
  generate,
}
/* leetMap Not a pure module */
