// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Generators from "./Generators.res.js";

function algorithmFromString(s) {
  switch (s) {
    case "md5" :
      return "MD5";
    case "sha1" :
      return "SHA1";
    case "sha256" :
      return "SHA256";
    case "sha512" :
      return "SHA512";
    default:
      return;
  }
}

function algorithmToString(a) {
  switch (a) {
    case "MD5" :
      return "md5";
    case "SHA1" :
      return "sha1";
    case "SHA256" :
      return "sha256";
    case "SHA512" :
      return "sha512";
  }
}

function algorithmToWebCrypto(a) {
  switch (a) {
    case "MD5" :
      return;
    case "SHA1" :
      return "SHA-1";
    case "SHA256" :
      return "SHA-256";
    case "SHA512" :
      return "SHA-512";
  }
}

function expectedLength(a) {
  switch (a) {
    case "MD5" :
      return 32;
    case "SHA1" :
      return 40;
    case "SHA256" :
      return 64;
    case "SHA512" :
      return 128;
  }
}

function isValidHash(hash, algo) {
  let len = expectedLength(algo);
  if (hash.length === len) {
    return /^[a-fA-F0-9]+$/.test(hash);
  } else {
    return false;
  }
}

let Subtle = {};

let Crypto = {
  Subtle: Subtle
};

let TextEncoder = {};

function bufferToHex(buffer) {
  let bytes = new Uint8Array(buffer);
  let result = "";
  for (let i = 0, i_finish = bytes.byteLength; i < i_finish; ++i) {
    let byte = bytes[i];
    let hex = byte.toString(16);
    result = result + (
      hex.length === 1 ? "0" + hex : hex
    );
  }
  return result;
}

function md5Polyfill(str) {
  let hash = 0;
  for (let i = 0, i_finish = str.length; i < i_finish; ++i) {
    ((str.charCodeAt(i) | 0));
    hash = (((currentHash << 5) - currentHash + code) | 0);
  }
  let absHash = Math.abs(hash);
  let hex = (absHash | 0).toString(16);
  return hex.padStart(32, "0");
}

async function hashPassword(password, algo) {
  let algoName = algorithmToWebCrypto(algo);
  if (algoName === undefined) {
    return md5Polyfill(password);
  }
  let encoder = new TextEncoder();
  encoder.encode(password);
  let buffer = data.buffer;
  return bufferToHex(await crypto.subtle.digest(algoName, buffer));
}

async function crackHashFallback(targetHash, algo, genType, maxAttempts) {
  let attempts = 0;
  let found = false;
  let foundPassword;
  while (attempts < maxAttempts && !found) {
    let password = Generators.generate(genType, 1, 6, 16)[0];
    attempts = attempts + 1 | 0;
    let hash = await hashPassword(password, algo);
    if (hash.toLowerCase() === targetHash.toLowerCase()) {
      found = true;
      foundPassword = password;
    } else if (attempts % 1000 === 0) {
      await Promise.resolve();
    }
  };
  return {
    found: found,
    password: foundPassword,
    attempts: attempts
  };
}

let $$Math$1;

export {
  $$Math$1 as $$Math,
  algorithmFromString,
  algorithmToString,
  algorithmToWebCrypto,
  expectedLength,
  isValidHash,
  Crypto,
  TextEncoder,
  bufferToHex,
  md5Polyfill,
  hashPassword,
  crackHashFallback,
}
/* Generators Not a pure module */
