// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE


function notificationColor(t) {
  switch (t) {
    case "Success" :
      return "var(--color-success)";
    case "Error" :
      return "var(--color-error)";
    case "Warning" :
      return "var(--color-warning)";
    case "Info" :
      return "var(--color-info)";
  }
}

function show(message, notifType) {
  let color = notificationColor(notifType);
  let notification = document.createElement("div");
  notification.textContent = message;
  (((function(el, color) {
      el.style.cssText = 'position: fixed; bottom: 2rem; right: 2rem; background: ' + color +
        '; color: var(--color-bg-primary); padding: 1rem 1.5rem; border-radius: 8px;' +
        ' box-shadow: var(--shadow-lg); font-weight: 600; z-index: 10000;' +
        ' animation: slideIn 0.3s ease;';
    }))(notification, color));
  (document.body.appendChild(notification));
  ((setTimeout(function() {
      notification.style.animation = 'slideOut 0.3s ease';
      setTimeout(function() { notification.remove(); }, 300);
    }, 3000)));
}

export {
  notificationColor,
  show,
}
/* No side effect */
