// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE


function make(moduleName) {
  return {
    moduleName: moduleName,
    instance: null,
    memory: null,
    exports: null
  };
}

let WasmModule = {
  make: make
};

let defaultConfig_modules = [
  "leetspeak",
  "phonetic",
  "pattern",
  "random",
  "markov",
  "hash_cracker"
];

let defaultConfig = {
  wasmPath: "/static/wasm/",
  modules: defaultConfig_modules,
  timeout: 10000
};

function make$1() {
  return {
    modules: {},
    ready: false,
    errors: [],
    config: defaultConfig
  };
}

let WasmRegistry = {
  defaultConfig: defaultConfig,
  make: make$1
};

let WebAssembly = {};

export {
  WasmModule,
  WasmRegistry,
  WebAssembly,
}
/* No side effect */
