// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE


let Element = {};

let Document = {};

let Window = {};

let Console = {};

let Clipboard = {};

let Navigator = {
  Clipboard: Clipboard
};

let Performance = {};

let $$Math = {};

export {
  Element,
  Document,
  Window,
  Console,
  Navigator,
  Performance,
  $$Math,
}
/* No side effect */
